// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aaacsikmrbvenjafxnwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhYWNzaWttcmJ2ZW5qYWZ4bndlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMzkzNTcsImV4cCI6MjA3MDgxNTM1N30.I7w-EpN1AKjaqdO2dZSm7wJjmD7Jf0E_6GnJSCB8M7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});